### ISSUE TITLE
When I run this code, I get an error

### ISSUE THREAD

**Issue by by-ck** [YinghaoHuang91/MuVS#1]
from psbody.mesh import Mesh
ImportError: No module named mesh

**Comment by YinghaoHuang91** [comment]
Hi, thanks for reporting the error. Just updated the README file. To use the Mesh functionality, you need to install another library from this link: https://github.com/MPI-IS/meshlite/blob/master/mesh/mesh.py. It should do the work.

**Comment by by-ck** [comment]
Hi,it's not work.I have installed MeshLite，but it doesn't work. Still reported this error.
Can you check it? Are you sure that the MeshLite  you are using has not been modified?

**Comment by by-ck** [comment]
Thanks for your help,I have solved this error.

**Comment by aditi310896** [comment]
Hi @LoneRangerY I am getting the same error would you be able to explain what you did to solve the error?
