### ISSUE TITLE
The dynamic model sequence is shaking

### ISSUE THREAD

**Issue by lszh2015** [YinghaoHuang91/MuVS#11]
Hello Yinghao,

Thank you for your wonderful job! But there is a problem I met. When I run the demo code on data attached on the respository, the SMPL model fits well on every frame.  However, when I render the SMPL models as a consecutive video, the model is shaking. How to deal with this problem? Thank you!

**Comment by YinghaoHuang91** [comment]
Sorry for the late response. Can you please be more specific about the issue? May I ask where do you think the shaking comes from? The 3D model part or the rendering part? Please note you might want to add translation into the rendering pipeline.
