### ISSUE TITLE
Resulting shape and pose is not good.

### ISSUE THREAD

**Issue by abdullahchand** [YinghaoHuang91/MuVS#13]
Hi Yang! thanks for your awesome work!

i have been having issues while testing it. Testing it on the data that you provide (as it is) turns out a pretty good shape and pose. But when I try to test on videos taken from CMU Panoptic dataset or any other video. The resulting shape and pose comes out very poor. I also inputted the right camera parameters. Can it be the format of the camera parameters input or some kind of scaling required? Can you tell me how you represent the camera parameters? . I also used 3 views and also tried on 4 views. None of it seems to work.

I read the camera parameters from the CMU panoptic datasets calibration.json and I convert them to np.float32 before passing to the function. Can it be something there?.

Regards

**Comment by williammm001** [comment]
Hi @abdullahchand, I also have the same problem. Actually, if I used the camera parameters the author provided on my own video, the results is OK. But if I inputted my camera parameters, the results are poor for most of the frames. I guess there might be some issues about the format of the camera parameters. I noticed that in the camera.py the T is divided by 1000, I multiply it on my own parameters but it doesn't work.

Would you mind telling me if you solved this problem?

**Comment by abdullahchand** [comment]
Hi @ZhiweiREN97 . I actually I was able to solve it for most of the videos. I was able to get the intrinsic parameters correct and used the extrinsic parameters from the default camera.mat. They worked well but not for all Videos. In SMPLfy the authors predict the extrinsic parameters through fitting the model and only need the extrinsic parameters in there. The problem comes buecause in this repository, that feature has been replaced by absolute parameters. We have to give extrinsic and intrinsic parameters.

**Comment by williammm001** [comment]
Thanks @abdullahchand! I absolutely agree with you. I also found out that if I use my own intrinsic parameters and keep the default exterinsic parameters unchanged, the results are much better than I use both intrinsic and extrinsic parameters of my own. However, I need to projected the mesh back to the images which is not good enough if the extrinsic parameters are not changed. I guess the problem is the bad initial parameters. I would update it if I found a perfect solution to that.

**Comment by williammm001** [comment]
Hi @abdullahchand! I found a temporary solution for this. You can use your own camera parameters and you need to multiply the "t" by 1000 (at least for me that works). Then, you may choose two views with a good deepcut result. The loss get to 10e2 for me which is much better than before.
