### ISSUE TITLE
Switch to OpenPose from LSP

### ISSUE THREAD

**Issue by wine3603** [YinghaoHuang91/MuVS#15]
Hi @YinghaoHuang91  I am switching to Openpose as a joint detector for MuVS.
I read the codes of SMPL-X, I will refer to their way. I have a question about this line:
https://github.com/YinghaoHuang91/MuVS/blob/199f51e7450c69728df59486b61f6f092fade296/Code_TF/util.py#L28
I understand that the former line is to map LSP joints to SMPL's, and this torso joints are the 4 SMPL torso joints, but what are these 3-1, 4-1, 9-1, and 10-1?

**Comment by YinghaoHuang91** [comment]
This is the major body joints to quickly initialize the body orientation. The indices (3, 4, 9, 10) are 1-st based, thus -1 makes them 0-based. Actually with enough views this step can be safely ignored.

**Comment by wine3603** [comment]
@YinghaoHuang91 Thank you very much for the reply!
Then what is the Head_VID mean? 
https://github.com/YinghaoHuang91/MuVS/blob/199f51e7450c69728df59486b61f6f092fade296/Code_TF/util.py#L29
Does it mean the head top vertices ID of SMPL?
I saw in line 27 you map the LSP keypoint to SMPL's, and the headtop keypoint was not read into line SMPL_JOINTS_IDS,
https://github.com/YinghaoHuang91/MuVS/blob/199f51e7450c69728df59486b61f6f092fade296/Code_TF/util.py#L27
how did you deal with the headtop keypoint?
I have some problem about how do map the openpose nose point to SMPL jaw.

**Comment by YinghaoHuang91** [comment]
The HEAD_VID is used in Line 41 of file "smpl_batch.py". Yes it's the SMPL vertex index to act as the proxy for head 2D landmark. Since SMPL doesn't have facial landmarks, one way is to manually pick the close vertices. You can do the same thing for other 2D landmarks if you want to stick with SMPL. Or you can try other more recent version of SMPL, like SMPL-X or STAR.

**Comment by wine3603** [comment]
thanks for quick reply!
I got this, so where can I check these VIDs of SMPL vertices? e.g. I want to find the nose, eyes and ears for openpose corresponding. 
I considered about using SMPL-X, but their works mainly used python3.6....

**Comment by wine3603** [comment]
I found the nose_vid in smplx repo's smpl-h vid doc, but I haven't test it.
