### ISSUE TITLE
Can not see code about shape.

### ISSUE THREAD

**Issue by shanYanGuan** [YinghaoHuang91/MuVS#4]
I have saw 'Prior_Shape', but seems different from the description in paper.

**Comment by YinghaoHuang91** [comment]
Yeah you are right. The prior weight for shape vector is not considered in this demo code. The weight is the same as the one used in SMPLify (http://files.is.tue.mpg.de/black/papers/BogoECCV2016.pdf, Eq. 9), and the code link for SMPLify: https://bitbucket.org/Chipe1/smplify.

**Comment by shanYanGuan** [comment]
Great! Help me so much. Thank you!

**Comment by naren142** [comment]
@mehameha998 hey hi...can I get your email address?

**Comment by mehameha998** [comment]
My honor! E-mail:shyanguan@gmail.com @naren142
