### ISSUE TITLE
With a larger picture like 1024*1024, the train results poor loss like 10E6

### ISSUE THREAD

**Issue by MisssRain** [YinghaoHuang91/MuVS#5]
I replace the data used in the project with 1024*1024 jpg, also 14 2d joints involved.
While the loss result turns out to be extraordinarily large: 
```
Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    6     23     26      1     0     0   1.000D+06   7.801D+06
  F =   7800716.0000000000
```

Does the picture size matter with the training? Or anything I missed then.

**Comment by YinghaoHuang91** [comment]
Do you mean that you tried the code on your own dataset? If so you need to update the settings like camera parameters and image size accordingly.

**Comment by MisssRain** [comment]
Thanks a lot! I figured out that it was our camera's extrinsic parameter, transpose matrix, that has already been divided by 1000.0. The loss function falls down to 10E4 for pose(\thetas) and shape(\betas) parameters in smpl then. 
The training result projected to 2d image was not good enough under condition that we have 8 camera views...
Another question: I didn't find where to set the picture size in your code, does it matter for the training? Or if I should change the Data/genericPrior.mat?

**Comment by YinghaoHuang91** [comment]
You need to dig deep about how camera parameters are represented. I think this link might help you a lot: https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html.

**Comment by MisssRain** [comment]
Thanks very much! Really a great help!
