### ISSUE TITLE
The result shape is strange

### ISSUE THREAD

**Issue by lszh2015** [YinghaoHuang91/MuVS#8]
Hello Yinghao, thank you for your wonderful idea and open source. When I run the demo without any change, the reconstructed model is strange especially the pose of head, and the loss of optimization is about 5000. I also tested only using 1 view, the result is much worse than the Smplify Tensorflow edition. Is that the reason of configuration? Thank you for your help!

**Comment by YinghaoHuang91** [comment]
Hi, thanks for pointing this out! The head pose is really weird.

For the time being, can you please do this operation inside the repository: git checkout 9354c87f5b7c7ab4415e653acc17af152e699b5a? After that everything is back to normal again. 

I suppose something is wrongly changed during later update. I will correct the issue once I figure out what the exact cause is. Thanks again.

**Comment by lszh2015** [comment]
Thank you, it really helps! I hope to consult you another question. In the 2D pose estimation, you seem using LSP as the joint descriptor, and gave out the correspondence with SMPL joints. However, Openpose only provides Body25, COCO. How can I prepare my own data? Thanks.

**Comment by YinghaoHuang91** [comment]
For this you need to assign some detected 2D joints to corresponding 3D SMPL joints, the mapping information is explicitly defined. A good reference for more details can be the more recent CVPR-19 paper: [](https://ps.is.tuebingen.mpg.de/publications/smplex-2019), and its released code: [](https://github.com/vchoutas/smplify-x). I believe there OpenPose is utilized.

**Comment by lszh2015** [comment]
Thank you for your sincere help! I have solved my problem.

**Comment by wine3603** [comment]
@lszh2015 hi, man, did you find the way to use openpose input for this repo?  I met this question too.
