### ISSUE TITLE
About camera pose

### ISSUE THREAD

**Issue by sta105** [YinghaoHuang91/MuVS#9]
How do you get the camera extrinsic from human3.6m dataset?

**Comment by YinghaoHuang91** [comment]
Hi for H3.6M camera settings I directly used the ones shared at our group internally. I suppose you can get it from the H3.6M website: http://vision.imar.ro/human3.6m/description.php. Maybe SURREAL is one helpful place to refer to: https://github.com/gulvarol/surreal.
